micronaut:
  application:
    name: micronaut
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update


datasources:
  default:
    dbCreate: update
    pooled: true
    jmxExport: true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: ''
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    url: jdbc:mysql://localhost:3306/micronaut
